# Generated by Django 5.0 on 2023-12-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tecnica', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Knit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tecnica', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='')),
                ('instrucciones', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
