# Generated by Django 5.0 on 2023-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/accesorios'),
        ),
        migrations.AlterField(
            model_name='knit',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/tejidos'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/hilados'),
        ),
    ]
