# Generated by Django 5.0 on 2023-12-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_accessories_imagen_alter_knit_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios'),
        ),
        migrations.AlterField(
            model_name='knit',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tejidos'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hilados'),
        ),
    ]
