# Generated by Django 5.0 on 2023-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_accessories_imagen_alter_knit_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knit',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/tejidos'),
        ),
    ]
