# Generated by Django 5.0 on 2023-12-24 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_accessories_fecha_alter_knit_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 22, 31, 42, 869502)),
        ),
        migrations.AlterField(
            model_name='accessoriescomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 22, 31, 42, 870500)),
        ),
        migrations.AlterField(
            model_name='knit',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 22, 31, 42, 867432)),
        ),
        migrations.AlterField(
            model_name='knitcomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 22, 31, 42, 867432)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 22, 31, 42, 868502)),
        ),
        migrations.AlterField(
            model_name='yarncomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 22, 31, 42, 869502)),
        ),
    ]
