# Generated by Django 5.0 on 2023-12-24 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_accessories_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 46, 27, 129653)),
        ),
        migrations.AlterField(
            model_name='accessoriescomment',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='accessoriescomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 46, 27, 130653)),
        ),
        migrations.AlterField(
            model_name='knit',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='knit',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 46, 27, 127626)),
        ),
        migrations.AlterField(
            model_name='knitcomment',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='knitcomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 46, 27, 128660)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 46, 27, 128660)),
        ),
        migrations.AlterField(
            model_name='yarncomment',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='yarncomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 46, 27, 129653)),
        ),
    ]
