# Generated by Django 5.0 on 2023-12-24 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_accessories_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfinishedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.ImageField(upload_to='fondos')),
            ],
        ),
        migrations.AlterField(
            model_name='accessories',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 14, 38, 17, 189887)),
        ),
        migrations.AlterField(
            model_name='accessoriescomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 14, 38, 17, 190985)),
        ),
        migrations.AlterField(
            model_name='knit',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 14, 38, 17, 186896)),
        ),
        migrations.AlterField(
            model_name='knitcomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 14, 38, 17, 187895)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 14, 38, 17, 188890)),
        ),
        migrations.AlterField(
            model_name='yarncomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 14, 38, 17, 188890)),
        ),
    ]
