# Generated by Django 5.0 on 2023-12-26 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_unfinishedpage_alter_accessories_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 40, 21, 145348)),
        ),
        migrations.AlterField(
            model_name='accessoriescomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 40, 21, 147383)),
        ),
        migrations.AlterField(
            model_name='knit',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 40, 21, 117233)),
        ),
        migrations.AlterField(
            model_name='knitcomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 40, 21, 125716)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 40, 21, 134689)),
        ),
        migrations.AlterField(
            model_name='yarncomment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 15, 40, 21, 142318)),
        ),
    ]
